# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: will-paginate-i18n 0.1.15 ruby lib

Gem::Specification.new do |s|
  s.name = "will-paginate-i18n"
  s.version = "0.1.15"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Christopher Dell"]
  s.date = "2014-06-04"
  s.description = "Translations for the will_paginate gem"
  s.email = "chris@tigrish.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/will-paginate-i18n.rb",
    "locales/bg.yml",
    "locales/ca.yml",
    "locales/da.yml",
    "locales/de.yml",
    "locales/en-AU.yml",
    "locales/en-GB.yml",
    "locales/en.yml",
    "locales/es.yml",
    "locales/fi.yml",
    "locales/fr.yml",
    "locales/hu.yml",
    "locales/it.yml",
    "locales/ja.yml",
    "locales/nl.yml",
    "locales/pl.yml",
    "locales/pt-BR.yml",
    "locales/pt.yml",
    "locales/ro.yml",
    "locales/ru.yml",
    "locales/sk.yml",
    "locales/sv.yml",
    "locales/tr.yml",
    "locales/uk.yml",
    "locales/zh-CN.yml",
    "locales/zh-TW.yml",
    "spec/spec_helper.rb",
    "spec/will-paginate-i18n_spec.rb",
    "will-paginate-i18n.gemspec"
  ]
  s.homepage = "http://github.com/tigrish/will-paginate-i18n"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Translations for the will_paginate gem"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<i18n-spec>, [">= 0"])
      s.add_development_dependency(%q<localeapp>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<i18n-spec>, [">= 0"])
      s.add_dependency(%q<localeapp>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<i18n-spec>, [">= 0"])
    s.add_dependency(%q<localeapp>, [">= 0"])
  end
end

